namespace ObsidianX.Core.Models;

public class PeerInfo
{
    public string BrainAddress { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
    public string PublicKey { get; set; } = string.Empty;
    public string Endpoint { get; set; } = string.Empty;
    public PeerStatus Status { get; set; } = PeerStatus.Offline;
    public Dictionary<KnowledgeCategory, double> ExpertiseScores { get; set; } = new();
    public long TotalKnowledgeNodes { get; set; }
    public long TotalWords { get; set; }
    public DateTime LastSeen { get; set; }
    public DateTime JoinedAt { get; set; }
    public double ReputationScore { get; set; } = 0.5;
    public int SharedCount { get; set; }
    public int ReceivedCount { get; set; }
}

public enum PeerStatus
{
    Online,
    Offline,
    Busy,
    Sharing,
    Requesting
}

public class MatchRequest
{
    public string RequesterAddress { get; set; } = string.Empty;
    public KnowledgeCategory DesiredCategory { get; set; }
    public List<string> Keywords { get; set; } = [];
    public double MinExpertiseScore { get; set; } = 0.3;
    public int MaxResults { get; set; } = 10;
}

public class MatchResult
{
    public PeerInfo Peer { get; set; } = new();
    public double MatchScore { get; set; }
    public KnowledgeCategory MatchedCategory { get; set; }
    public string MatchReason { get; set; } = string.Empty;
}

public class ShareRequest
{
    public string FromAddress { get; set; } = string.Empty;
    public string ToAddress { get; set; } = string.Empty;
    public string NodeTitle { get; set; } = string.Empty;

    /// <summary>Stable identifier (note id or path) — required so the
    /// requester can match the eventual <see cref="ShareEnvelope"/> back
    /// to this request. <see cref="NodeTitle"/> stays for UI display.</summary>
    public string NodeId { get; set; } = string.Empty;

    public KnowledgeCategory Category { get; set; }
    public int WordCount { get; set; }

    /// <summary>
    /// PR #6 — random per-request nonce (≥16 bytes base64) that the server
    /// remembers for 5 min to defeat replay. Pair this with <see cref="IssuedAt"/>
    /// for clock-skew bounding. Required: hub rejects empty.
    /// </summary>
    public string Nonce { get; set; } = string.Empty;

    /// <summary>
    /// PR #6 — UTC moment the requester signed this. Server rejects if it's
    /// more than ±30s off wall clock; bounds the replay window even if a
    /// nonce somehow leaks the seen-cache (server restart, etc).
    /// </summary>
    public DateTime IssuedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Owner's signature over the canonical bytes of this request (see
    /// <see cref="ObsidianX.Core.Services.ShareRequestSigner"/>). PR #6 wires
    /// the hub to verify this — pre-PR #6 the field was set but ignored.
    /// </summary>
    public string Signature { get; set; } = string.Empty;

    public DateTime RequestedAt { get; set; } = DateTime.UtcNow;
    public ShareStatus Status { get; set; } = ShareStatus.Pending;

    /// <summary>
    /// PR #5 — base64 of a per-request ECDH-P256 public key generated by
    /// the requester. The owner combines this with its long-term private
    /// key to derive the AES-GCM session key. Empty in pre-E2E clients —
    /// the owner refuses to send content when this is empty.
    /// </summary>
    public string RequesterEphemeralPublicKey { get; set; } = string.Empty;
}

public enum ShareStatus
{
    Pending,
    Accepted,
    Rejected,
    Completed,
    Cancelled
}
