using System.IO;
using System.IO.Pipes;
using System.Text;
using System.Text.Json;

namespace ObsidianX.Core.Services;

/// <summary>
/// Named-pipe MCP client for CluadeX's in-process host.
///
/// Why this exists
/// ---------------
/// CluadeX is a WPF agent app at E:\code\claudeclient\CluadeX. It exposes
/// its agentic-loop capabilities (48 tools, 15-iter loop, native tool_use,
/// skill system) over a per-user named pipe at <c>\\.\pipe\cluadex-mcp</c>.
/// We wire ObsidianX's "Co-Pilot Arena" to it so:
///
///     Local Ollama (intern, in ObsidianX) → CluadeXClient → CluadeX (worker)
///                                                  → diff back ← Claude Desktop reviewer
///
/// Each call to <see cref="WriteCodeAsync"/> spawns a NEW visible chat
/// session inside CluadeX so the user can scroll back and audit what the
/// worker did, separately from any interactive chat that's already open.
///
/// Threading
/// ---------
/// All public methods are <c>async</c> and safe to call from any thread.
/// Internally we serialise requests to the underlying pipe via a single
/// pending-request slot — JSON-RPC IDs guarantee correlation, but we
/// keep it 1-at-a-time per <see cref="CluadeXClient"/> instance for
/// debuggability. Spin up multiple clients if you need parallelism.
///
/// Authentication
/// --------------
/// CluadeX writes a 32-byte random auth token to
/// <c>%USERPROFILE%\.cluadex\mcp-host-token</c> on first run. We read it,
/// pass it as <c>initialize.params.authToken</c>, and CluadeX accepts the
/// connection. The pipe itself is restricted by Windows ACL to the
/// current user — the auth token is a second factor in case multiple
/// trusted apps share the host but should be isolated by capability.
/// </summary>
public sealed class CluadeXClient : IAsyncDisposable
{
    /// <summary>Default pipe name CluadeX listens on. Override in tests.</summary>
    public const string DefaultPipeName = "cluadex-mcp";

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    private readonly string _pipeName;
    private readonly string _tokenPath;
    private readonly SemaphoreSlim _sendLock = new(1, 1);
    /// <summary>Guards <see cref="EnsureConnectedAsync"/> so two callers
    /// from different threads can't both open a pipe + handshake — that
    /// raced under the previous design and left an orphan StreamReader.</summary>
    private readonly SemaphoreSlim _connectLock = new(1, 1);
    private NamedPipeClientStream? _pipe;
    private StreamReader? _reader;
    private StreamWriter? _writer;
    private int _nextId;
    private bool _initialised;
    private string? _authToken;
    private bool _disposed;

    public CluadeXClient(string? pipeName = null, string? tokenPath = null)
    {
        _pipeName = pipeName ?? DefaultPipeName;
        _tokenPath = tokenPath ?? Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".cluadex", "mcp-host-token");
    }

    public bool IsConnected => _pipe?.IsConnected == true;

    /// <summary>
    /// Hook for the orchestrator to launch (and if necessary install) the
    /// CluadeX worker before we connect. Called once when
    /// <see cref="EnsureConnectedAsync"/> can't reach the pipe. Returning
    /// <c>true</c> means "I started it — go ahead and retry the connect".
    /// Falls back to throwing if the hook is null or returns false.
    /// </summary>
    public Func<CancellationToken, Task<bool>>? OnNeedLaunch { get; set; }

    /// <summary>Connect to the CluadeX named pipe and complete the MCP
    /// initialize handshake. Idempotent — calling twice is a no-op once
    /// the connection is healthy.</summary>
    public async Task EnsureConnectedAsync(int connectTimeoutMs = 3000, CancellationToken ct = default)
    {
        // Fast-path: already healthy
        if (IsConnected && _initialised) return;

        // Connect-side lock so concurrent callers don't double-handshake.
        await _connectLock.WaitAsync(ct);
        try
        {
            // Re-check inside the lock — another thread may have completed
            // the handshake while we were waiting for the semaphore.
            if (IsConnected && _initialised) return;

            // Tear down any half-built state from a prior failed attempt
            // before trying again. Otherwise a leaked StreamReader could
            // outlive the pipe.
            ResetTransport();

            // Step 1: ensure the CluadeX auth token exists on disk. This is
            // generated by CluadeX on first launch — if the user hasn't run
            // CluadeX yet, ask the launcher hook to start it. We retry the
            // file read up to 5s after launch since the token write happens
            // ~1s into App.OnStartup.
            if (!File.Exists(_tokenPath))
            {
                if (OnNeedLaunch != null && await OnNeedLaunch(ct))
                {
                    if (!await WaitForFileAsync(_tokenPath, TimeSpan.FromSeconds(15), ct))
                    {
                        throw new InvalidOperationException(
                            $"Launched CluadeX but auth token never appeared at {_tokenPath}.");
                    }
                }
                else
                {
                    throw new InvalidOperationException(
                        $"CluadeX auth token not found at {_tokenPath}. " +
                        "Either start CluadeX manually or wire OnNeedLaunch to auto-launch it.");
                }
            }
            _authToken = (await File.ReadAllTextAsync(_tokenPath, ct)).Trim();
            if (string.IsNullOrWhiteSpace(_authToken))
                throw new InvalidOperationException($"Auth token at {_tokenPath} is empty");

            // Step 2: try to connect. If the pipe isn't there yet, give the
            // launcher one chance to spin up CluadeX, then retry.
            if (!await TryConnectOnceAsync(connectTimeoutMs, ct))
            {
                if (OnNeedLaunch != null && await OnNeedLaunch(ct))
                {
                    // Wait up to 20s for the pipe to appear after launch.
                    if (!await TryConnectOnceAsync(20_000, ct))
                    {
                        throw new InvalidOperationException(
                            "Launched CluadeX but pipe never came online. Check its log at " +
                            "%USERPROFILE%/.cluadex/mcp-host.log");
                    }
                }
                else
                {
                    throw new InvalidOperationException(
                        $"Timed out connecting to \\\\.\\pipe\\{_pipeName} after {connectTimeoutMs}ms. " +
                        "Is CluadeX running? (Look for the bridge chip in its sidebar.)");
                }
            }

            _reader = new StreamReader(_pipe!, Encoding.UTF8, leaveOpen: true);
            _writer = new StreamWriter(_pipe!, new UTF8Encoding(false), 64 * 1024, leaveOpen: true)
            {
                AutoFlush = true,
                NewLine = "\n",
            };

            // Step 3: handshake with the auth token.
            var initResp = await SendRequestRawAsync(
                "initialize",
                new { authToken = _authToken },
                timeoutMs: 5000, ct);
            if (initResp.Error != null)
            {
                throw new InvalidOperationException(
                    $"initialize rejected: {initResp.Error.Code} {initResp.Error.Message}");
            }
            _initialised = true;
        }
        finally
        {
            _connectLock.Release();
        }
    }

    /// <summary>One ConnectAsync attempt. Returns true on success,
    /// false on TimeoutException — every other exception bubbles.</summary>
    private async Task<bool> TryConnectOnceAsync(int timeoutMs, CancellationToken ct)
    {
        _pipe?.Dispose();
        _pipe = new NamedPipeClientStream(
            ".",                  // local machine — CluadeX always runs locally
            _pipeName,
            PipeDirection.InOut,
            PipeOptions.Asynchronous);
        try
        {
            await _pipe.ConnectAsync(timeoutMs, ct);
            return true;
        }
        catch (TimeoutException)
        {
            _pipe.Dispose();
            _pipe = null;
            return false;
        }
    }

    private void ResetTransport()
    {
        try { _writer?.Dispose(); } catch { }
        try { _reader?.Dispose(); } catch { }
        try { _pipe?.Dispose(); } catch { }
        _writer = null;
        _reader = null;
        _pipe = null;
        _initialised = false;
    }

    /// <summary>Poll for a file's existence with a short delay between
    /// checks. Used after launching CluadeX while waiting for it to write
    /// the auth-token file.</summary>
    private static async Task<bool> WaitForFileAsync(string path, TimeSpan timeout, CancellationToken ct)
    {
        var deadline = DateTime.UtcNow + timeout;
        while (DateTime.UtcNow < deadline)
        {
            if (File.Exists(path)) return true;
            try { await Task.Delay(250, ct); }
            catch (OperationCanceledException) { return false; }
        }
        return File.Exists(path);
    }

    /// <summary>List the tools the host advertises. Returns the raw
    /// JsonElement so callers can introspect schemas without a strong
    /// model dependency.</summary>
    public async Task<JsonElement> ListToolsAsync(CancellationToken ct = default)
    {
        await EnsureConnectedAsync(ct: ct);
        var resp = await SendRequestRawAsync("tools/list", null, timeoutMs: 5000, ct);
        ThrowIfError(resp);
        return resp.Result ?? default;
    }

    /// <summary>Delegate a coding task to CluadeX. Spawns a NEW visible
    /// chat session inside the running CluadeX UI tagged with the caller's
    /// task id. Returns the agent's final reply (typically a diff plus
    /// rationale). Use this for the orchestrator's worker step.</summary>
    public async Task<string> WriteCodeAsync(
        string taskId,
        string spec,
        IReadOnlyList<string>? lessons = null,
        IReadOnlyList<string>? contextFiles = null,
        string? workingDirectory = null,
        int timeoutMs = 5 * 60 * 1000,
        CancellationToken ct = default)
    {
        await EnsureConnectedAsync(ct: ct);
        var resp = await SendRequestRawAsync("tools/call", new
        {
            name = "cluadex.write_code",
            arguments = new
            {
                taskId,
                spec,
                lessons,
                contextFiles,
                workingDirectory,
            }
        }, timeoutMs, ct);
        ThrowIfError(resp);
        return ExtractToolText(resp.Result);
    }

    /// <summary>Run one of CluadeX's slash-skills (e.g. <c>commit</c>,
    /// <c>review-pr</c>, <c>simplify</c>). Same visibility semantics as
    /// <see cref="WriteCodeAsync"/>.</summary>
    public async Task<string> RunSkillAsync(
        string taskId,
        string skill,
        string? args = null,
        string? workingDirectory = null,
        int timeoutMs = 5 * 60 * 1000,
        CancellationToken ct = default)
    {
        await EnsureConnectedAsync(ct: ct);
        var resp = await SendRequestRawAsync("tools/call", new
        {
            name = "cluadex.run_skill",
            arguments = new
            {
                taskId,
                skill,
                args,
                workingDirectory,
            }
        }, timeoutMs, ct);
        ThrowIfError(resp);
        return ExtractToolText(resp.Result);
    }

    /// <summary>Ask CluadeX to review a diff. Cheaper than sending to the
    /// Claude Desktop senior reviewer — used as a pre-filter so obvious
    /// bugs get caught before the human-in-loop step.</summary>
    public async Task<string> ReviewAsync(
        string taskId,
        string diff,
        string? intent = null,
        int timeoutMs = 2 * 60 * 1000,
        CancellationToken ct = default)
    {
        await EnsureConnectedAsync(ct: ct);
        var resp = await SendRequestRawAsync("tools/call", new
        {
            name = "cluadex.review",
            arguments = new
            {
                taskId,
                diff,
                intent,
            }
        }, timeoutMs, ct);
        ThrowIfError(resp);
        return ExtractToolText(resp.Result);
    }

    /// <summary>Ask CluadeX which provider+model it has loaded right now.
    /// Used for the model-alignment guard: ObsidianX's intern and CluadeX
    /// must run the SAME local model or they'll fight over GPU memory.</summary>
    public async Task<CluadeXModelInfo> GetActiveModelAsync(int timeoutMs = 5000, CancellationToken ct = default)
    {
        await EnsureConnectedAsync(ct: ct);
        var resp = await SendRequestRawAsync("tools/call", new
        {
            name = "cluadex.get_active_model",
            arguments = new { },
        }, timeoutMs, ct);
        ThrowIfError(resp);
        string flat = ExtractToolText(resp.Result);
        if (string.IsNullOrWhiteSpace(flat))
            return new CluadeXModelInfo();
        try
        {
            return JsonSerializer.Deserialize<CluadeXModelInfo>(flat, JsonOpts)
                   ?? new CluadeXModelInfo();
        }
        catch
        {
            return new CluadeXModelInfo { Note = $"unparseable response: {flat}" };
        }
    }

    /// <summary>Force CluadeX to switch its active provider+model so it
    /// aligns with this app. Most common case: pass provider="Ollama" +
    /// model="qwen2.5:7b" so both ObsidianX intern and CluadeX worker
    /// use the same Ollama daemon entry → one model in VRAM, not two.
    /// Returns the result envelope as a parsed POCO. Throws if the
    /// switch failed at the protocol level (network / auth); a
    /// successful pipe call with provider-not-ready is reported via
    /// <c>Ready=false</c> on the returned object.</summary>
    public async Task<CluadeXSetModelResult> SetModelAsync(
        string provider,
        string model,
        string? path = null,
        int timeoutMs = 30_000,
        CancellationToken ct = default)
    {
        await EnsureConnectedAsync(ct: ct);
        var resp = await SendRequestRawAsync("tools/call", new
        {
            name = "cluadex.set_model",
            arguments = new { provider, model, path },
        }, timeoutMs, ct);
        ThrowIfError(resp);
        string flat = ExtractToolText(resp.Result);
        if (string.IsNullOrWhiteSpace(flat))
            return new CluadeXSetModelResult { Note = "(empty response from CluadeX)" };
        try
        {
            return JsonSerializer.Deserialize<CluadeXSetModelResult>(flat, JsonOpts)
                   ?? new CluadeXSetModelResult();
        }
        catch
        {
            return new CluadeXSetModelResult { Note = $"unparseable response: {flat}" };
        }
    }

    /// <summary>Lightweight liveness probe. Doesn't run the agent — just
    /// confirms the pipe is open and responsive. Use this for a status
    /// chip refresh in the orchestrator UI.</summary>
    public async Task<bool> PingAsync(int timeoutMs = 2000, CancellationToken ct = default)
    {
        try
        {
            await EnsureConnectedAsync(ct: ct);
            var resp = await SendRequestRawAsync("ping", null, timeoutMs, ct);
            return resp.Error == null;
        }
        catch
        {
            return false;
        }
    }

    // ─── Internal: JSON-RPC plumbing ─────────────────────────────────────

    private async Task<JsonRpcInboundResponse> SendRequestRawAsync(
        string method, object? parameters, int timeoutMs, CancellationToken ct)
    {
        if (_pipe is null || _writer is null || _reader is null)
            throw new InvalidOperationException("Pipe not connected. Call EnsureConnectedAsync first.");

        await _sendLock.WaitAsync(ct);
        try
        {
            int id = Interlocked.Increment(ref _nextId);
            var request = new JsonRpcOutboundRequest
            {
                Jsonrpc = "2.0",
                Id = id,
                Method = method,
                Params = parameters,
            };
            string requestJson = JsonSerializer.Serialize(request, JsonOpts);
            await _writer.WriteLineAsync(requestJson.AsMemory(), ct);

            // Read until we get the matching id. Concurrency is impossible
            // because of the semaphore, but the server may emit
            // notifications (id-less) we want to skip.
            using var timeoutCts = CancellationTokenSource.CreateLinkedTokenSource(ct);
            timeoutCts.CancelAfter(timeoutMs);

            while (!timeoutCts.IsCancellationRequested)
            {
                string? line = await _reader.ReadLineAsync(timeoutCts.Token);
                if (line == null) throw new IOException("CluadeX pipe closed unexpectedly");
                if (string.IsNullOrWhiteSpace(line)) continue;

                JsonRpcInboundResponse? resp;
                try
                {
                    resp = JsonSerializer.Deserialize<JsonRpcInboundResponse>(line, JsonOpts);
                }
                catch (JsonException jx)
                {
                    throw new InvalidDataException($"Malformed response from CluadeX: {jx.Message}\n{line}");
                }
                if (resp == null) continue;
                if (resp.Id == id) return resp;
                // Otherwise it's a stray notification or response to an old
                // request — skip and keep reading.
            }

            throw new TimeoutException(
                $"CluadeX did not respond to '{method}' (id={id}) within {timeoutMs}ms");
        }
        finally
        {
            _sendLock.Release();
        }
    }

    private static void ThrowIfError(JsonRpcInboundResponse resp)
    {
        if (resp.Error == null) return;
        throw new InvalidOperationException(
            $"CluadeX error {resp.Error.Code}: {resp.Error.Message}");
    }

    /// <summary>Pull the flat text out of an MCP <c>tools/call</c> result.
    /// We're tolerant about shape — a hand-written CluadeX may return a
    /// bare string (legacy) or the proper <c>{ content: [{ type:'text',
    /// text:... }] }</c> envelope.</summary>
    private static string ExtractToolText(JsonElement? rawResult)
    {
        if (rawResult is not JsonElement el) return "";
        if (el.ValueKind == JsonValueKind.String) return el.GetString() ?? "";
        if (el.ValueKind != JsonValueKind.Object) return el.ToString();
        if (!el.TryGetProperty("content", out var content)) return el.ToString();
        if (content.ValueKind != JsonValueKind.Array) return content.ToString();
        var sb = new StringBuilder();
        foreach (var item in content.EnumerateArray())
        {
            if (item.ValueKind != JsonValueKind.Object) continue;
            if (!item.TryGetProperty("type", out var t)) continue;
            if (t.GetString() != "text") continue;
            if (item.TryGetProperty("text", out var txt) && txt.ValueKind == JsonValueKind.String)
            {
                if (sb.Length > 0) sb.AppendLine();
                sb.Append(txt.GetString());
            }
        }
        return sb.ToString();
    }

    public async ValueTask DisposeAsync()
    {
        if (_disposed) return;
        _disposed = true;
        try
        {
            _writer?.Dispose();
            _reader?.Dispose();
            if (_pipe is not null) await _pipe.DisposeAsync();
        }
        catch { /* best-effort */ }
        _sendLock.Dispose();
    }

    // ─── Tiny private DTOs ──────────────────────────────────────────────
    // Don't reuse CluadeX's JsonRpc* models here — keeping ObsidianX.Core
    // clean of cross-project copies. These mirror only what we need.

    private sealed class JsonRpcOutboundRequest
    {
        public string Jsonrpc { get; set; } = "2.0";
        public int Id { get; set; }
        public string Method { get; set; } = "";
        public object? Params { get; set; }
    }

    private sealed class JsonRpcInboundResponse
    {
        public string Jsonrpc { get; set; } = "2.0";
        public int? Id { get; set; }
        public JsonElement? Result { get; set; }
        public JsonRpcInboundError? Error { get; set; }
    }

    private sealed class JsonRpcInboundError
    {
        public int Code { get; set; }
        public string Message { get; set; } = "";
        public JsonElement? Data { get; set; }
    }
}

/// <summary>
/// What CluadeX has loaded. Returned by <see cref="CluadeXClient.GetActiveModelAsync"/>
/// and consumed by the model-alignment guard in the Co-Pilot Arena flow.
/// All fields nullable / defaulted so a partial response from an older
/// CluadeX build still deserialises.
/// </summary>
public sealed class CluadeXModelInfo
{
    /// <summary>"Local", "LlamaServer", "Ollama", "Anthropic", "OpenAI", "Gemini" — matches AiProviderType.ToString().</summary>
    public string Provider { get; set; } = "";
    /// <summary>Model name as the provider knows it (e.g. "qwen2.5:7b" for Ollama, "gemma-4-31B-it" for Local GGUF).</summary>
    public string Model { get; set; } = "";
    /// <summary>Full filesystem path of the .gguf file when Provider is Local. Empty for cloud / Ollama.</summary>
    public string Path { get; set; } = "";
    /// <summary>True if the active provider's IsReady gate is open — i.e. the model is loaded and warm.</summary>
    public bool Ready { get; set; }
    public int? VramUsedMB { get; set; }
    public int? VramTotalMB { get; set; }
    /// <summary>"OK" or a hint to surface to the user (e.g. "no model loaded").</summary>
    public string Note { get; set; } = "";

    /// <summary>Compact "provider:model" form for display + comparison.</summary>
    public string Identity =>
        string.IsNullOrEmpty(Model) ? $"{Provider}:(none)" : $"{Provider}:{Model}";
}

/// <summary>
/// Outcome of <see cref="CluadeXClient.SetModelAsync"/>. <see cref="Ok"/> is
/// the high-level "aligned and warm" verdict; <see cref="Ready"/> is the
/// raw provider readiness. <see cref="FreedLocalWeights"/> tells the
/// orchestrator whether the previous Local GGUF / LlamaServer model was
/// released — useful for VRAM accounting in a UI status chip.
/// </summary>
public sealed class CluadeXSetModelResult
{
    public bool Ok { get; set; }
    public string Provider { get; set; } = "";
    public string Model { get; set; } = "";
    public string Path { get; set; } = "";
    public bool Ready { get; set; }
    public string Note { get; set; } = "";
    public bool FreedLocalWeights { get; set; }
}

